namespace Beey.DataExchangeModel.Common.VoiceSamples.v1;

public class VoiceSampleDto
{
    /// <summary>Unique id assigned by the SpeakerCatalog</summary>
    public int Id { get; init; }

    public required string SpeakerId { get; set; }

    /// <summary>User-friendly file name suggestion provided by the uploader</summary>
    public required string? FileName { get; set; }

    /// <summary>File size in bytes determined by SpeakerCatalog from the data</summary>
    public long? FileLength { get; set; }

    /// <summary>If false, the file is not fully uploaded yet, is missing or something similar</summary>
    public required bool FileIsReady { get; set; }

    /// <summary>When was sample recorded; the information is provided by the sample uploader</summary>
    public required DateTimeOffset? Recorded { get; init; }

    /// <summary>When this entry was added to the SpeakerCatalog database</summary>
    public required DateTimeOffset? Uploaded { get; init; }

    /// <summary>Generated by the SpeakerCatalog, must be included in update requests</summary>
    public required string ConcurrencyToken { get; init; }
}
